import { Navbar } from "@/components/layout/Navbar";
import { Footer } from "@/components/layout/Footer";
import { resolveMetadata } from "@/lib/seo/resolveMetadata";
import { buildLandingMeta } from "@/lib/seo/metaFactories";

export const metadata = resolveMetadata(buildLandingMeta({
  title: "Terms of Service | Color Palette Generator",
  description: "Terms of Service for PaletteFlow. Read the terms, limitations, and license details for using our free color generator tool.",
  slug: "/terms",
}));

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background flex flex-col">
      <Navbar />
      <main className="flex-1 max-w-4xl mx-auto w-full px-6 py-20 space-y-12">
        <h1 className="text-5xl font-display font-bold">Terms of Service</h1>

        <div className="prose dark:prose-invert max-w-none text-text-secondary leading-relaxed space-y-6">
          <p>Last updated: January 1, 2026</p>

          <h2 className="text-2xl font-bold text-text-primary mt-8 mb-4">1. Acceptance of Terms</h2>
          <p>
            By accessing or using PaletteFlow, you agree to be bound by these Terms of Service.
            If you disagree with any part of the terms, you do not have permission to access the Service.
          </p>

          <h2 className="text-2xl font-bold text-text-primary mt-8 mb-4">2. Use License</h2>
          <p>
            PaletteFlow grants you a personal, non-exclusive, non-transferable, limited privilege to enter and use the Site.
            The color palettes generated by the tool are free to use for both personal and commercial projects without attribution.
          </p>
          <p>
            However, you may not:
          </p>
          <ul className="list-disc pl-6 space-y-2">
            <li>Attempt to reverse engineer any software contained on PaletteFlow</li>
            <li>Remove any copyright or other proprietary notations from the materials</li>
            <li>Use the service for any illegal or unauthorized purpose</li>
          </ul>

          <h2 className="text-2xl font-bold text-text-primary mt-8 mb-4">3. Disclaimer</h2>
          <p>
            The materials on PaletteFlow are provided on an &apos;as is&apos; basis. We make no warranties, expressed or implied,
            and hereby disclaim and negate all other warranties including, without limitation, implied warranties or
            conditions of merchantability, fitness for a particular purpose, or non-infringement of intellectual property
            or other violation of rights.
          </p>

          <h2 className="text-2xl font-bold text-text-primary mt-8 mb-4">4. Limitations</h2>
          <p>
            In no event shall PaletteFlow or its suppliers be liable for any damages (including, without limitation,
            damages for loss of data or profit, or due to business interruption) arising out of the use or inability to
            use the materials on PaletteFlow&apos;s website, even if PaletteFlow or an authorized representative has been notified
            orally or in writing of the possibility of such damage.
          </p>

          <h2 className="text-2xl font-bold text-text-primary mt-8 mb-4">5. Revisions and Errata</h2>
          <p>
            The materials appearing on PaletteFlow&apos;s website could include technical, typographical, or photographic errors.
            We do not warrant that any of the materials on its website are accurate, complete, or current. We may make changes
            to the materials contained on its website at any time without notice.
          </p>
        </div>
      </main>
      <Footer />
    </div>
  );
}
